#!/usr/bin/python3
"""Make docs/decisions-index.md from docs/decisions.md: the same rows, grouped by theme, one line each.

The log is one table of two hundred rows, in the order things happened, which is right for a record and
wrong for a person asking "why is the model service like that?". Themes are assigned by words in the row;
a row can be in more than one; a row that matches nothing goes under "Everything else" rather than being
lost. The first sentence of each row is its line. Run: python3 tools/decisions-index.py
"""
import re, pathlib, collections

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC, OUT = ROOT / "docs/decisions.md", ROOT / "docs/decisions-index.md"

THEMES = [
    ("Models and the router", r"\b(llama|router|llama-swap|model service|gguf|pack|ngl|vulkan|gpu|cpu|token|residency|swap|measure|genesis-pick-device|wrapper|embed)\b"),
    ("First run and the installer", r"\b(first run|wizard|install|installer|iso|anaconda|kickstart|account|firstuser|rootpw|usb)\b"),
    ("Updates, channels and the canary", r"\b(canary|stable|testing|bootc|upgrade|rollback|promot|release|channel|staged|update)\b"),
    ("The maker and the assistant", r"\b(maker|agent|agentd|session|chat|prompt|tool call|permission|broker|sandbox|bwrap|undo|mode)\b"),
    ("Crashes, failures and explaining the machine", r"\b(crash|coredump|segv|failed service|journal|genesis-crash|explain|failed unit)\b"),
    ("Looks, apps and the desktop", r"\b(theme|look|palette|wallpaper|konsole|plasma|kde|catalogue|flatpak|flathub|genesis-apps|desktop|icon)\b"),
    ("Battery and hardware", r"\b(battery|plug|power|laptop|nouveau|nvidia|amd|intel|arm64|apple silicon|hardware)\b"),
    ("Building, testing and CI", r"\b(build|ci|workflow|test|pytest|guard|shellcheck|runner|github actions|image size|containerfile|arm64 build)\b"),
    ("Words: README, manual, site, decisions", r"\b(readme|manual|front page|landing|site|docs|decision log|screenshot|video|clip)\b"),
    ("Security and privacy", r"\b(security|privacy|token|secret|password|leak|traversal|hostile|signed|cosign|policy|nothing leaves)\b"),
]

rows = []
for line in SRC.read_text().splitlines():
    m = re.match(r"^\| (\d+) \| (\d{4}-\d{2}-\d{2}) \| (.+?) \| (\w+) \|\s*$", line)
    if not m:
        continue
    n, date, text, status = m.groups()
    first = re.split(r"(?<=[.!?])\s", text.strip(), maxsplit=1)[0]
    if len(first) > 220:
        first = first[:217].rstrip() + "…"
    rows.append((int(n), date, first, text, status))

by = collections.OrderedDict((t, []) for t, _ in THEMES)
by["Everything else"] = []
for n, date, first, text, status in rows:
    hit = False
    for theme, pat in THEMES:
        if re.search(pat, text, re.I):
            by[theme].append((n, date, first)); hit = True
    if not hit:
        by["Everything else"].append((n, date, first))

out = ["# The decisions, by theme", "",
       f"{len(rows)} rows in [the log](decisions.md), in the order things happened. Here they are by what they are about — a row can appear under more than one theme — with the first sentence of each. Generated by `tools/decisions-index.py`; edit the log, not this.", ""]
for theme, items in by.items():
    if not items:
        continue
    out.append(f"## {theme} ({len(items)})"); out.append("")
    for n, date, first in sorted(items, key=lambda r: -r[0]):
        out.append(f"- **{n}** · {date} · {first}")
    out.append("")
OUT.write_text("\n".join(out))
print(f"{len(rows)} rows -> {OUT.relative_to(ROOT)}; " + ", ".join(f"{t}: {len(i)}" for t, i in by.items() if i))
